import { Transaction } from "@/types/types";

export const mockTransactions: Transaction[] = [
  // January
  {
    id: "1",
    date: "2025-01-05",
    amount: 85000,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
  },
  {
    id: "2",
    date: "2025-01-07",
    amount: 3200,
    category: "Food & Dining",
    type: "expense",
    description: "Grocery shopping",
  },
  {
    id: "3",
    date: "2025-01-10",
    amount: 1500,
    category: "Transport",
    type: "expense",
    description: "Ride share & fuel",
  },
  {
    id: "4",
    date: "2025-01-12",
    amount: 12000,
    category: "Housing",
    type: "expense",
    description: "Monthly rent",
  },
  {
    id: "5",
    date: "2025-01-15",
    amount: 5000,
    category: "Freelance",
    type: "income",
    description: "Web design project",
  },
  {
    id: "6",
    date: "2025-01-18",
    amount: 2800,
    category: "Shopping",
    type: "expense",
    description: "Clothing & accessories",
  },
  {
    id: "7",
    date: "2025-01-20",
    amount: 900,
    category: "Entertainment",
    type: "expense",
    description: "Streaming & gaming",
  },
  {
    id: "8",
    date: "2025-01-22",
    amount: 1100,
    category: "Utilities",
    type: "expense",
    description: "Electricity & internet",
  },
  {
    id: "9",
    date: "2025-01-25",
    amount: 2000,
    category: "Investment",
    type: "income",
    description: "Dividend received",
  },
  {
    id: "10",
    date: "2025-01-28",
    amount: 750,
    category: "Health",
    type: "expense",
    description: "Gym & pharmacy",
  },

  // February
  {
    id: "11",
    date: "2025-02-05",
    amount: 85000,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
  },
  {
    id: "12",
    date: "2025-02-08",
    amount: 4100,
    category: "Food & Dining",
    type: "expense",
    description: "Restaurants & groceries",
  },
  {
    id: "13",
    date: "2025-02-10",
    amount: 12000,
    category: "Housing",
    type: "expense",
    description: "Monthly rent",
  },
  {
    id: "14",
    date: "2025-02-13",
    amount: 3500,
    category: "Freelance",
    type: "income",
    description: "Logo design",
  },
  {
    id: "15",
    date: "2025-02-15",
    amount: 6200,
    category: "Shopping",
    type: "expense",
    description: "Electronics",
  },
  {
    id: "16",
    date: "2025-02-18",
    amount: 1800,
    category: "Transport",
    type: "expense",
    description: "Uber & CNG",
  },
  {
    id: "17",
    date: "2025-02-20",
    amount: 500,
    category: "Health",
    type: "expense",
    description: "Doctor visit",
  },
  {
    id: "18",
    date: "2025-02-22",
    amount: 1200,
    category: "Utilities",
    type: "expense",
    description: "Gas & electricity",
  },
  {
    id: "19",
    date: "2025-02-26",
    amount: 1500,
    category: "Entertainment",
    type: "expense",
    description: "Concert tickets",
  },
  {
    id: "20",
    date: "2025-02-28",
    amount: 3000,
    category: "Investment",
    type: "income",
    description: "Stock profit",
  },

  // March
  {
    id: "21",
    date: "2025-03-05",
    amount: 85000,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
  },
  {
    id: "22",
    date: "2025-03-07",
    amount: 3600,
    category: "Food & Dining",
    type: "expense",
    description: "Weekly groceries",
  },
  {
    id: "23",
    date: "2025-03-09",
    amount: 12000,
    category: "Housing",
    type: "expense",
    description: "Monthly rent",
  },
  {
    id: "24",
    date: "2025-03-12",
    amount: 8000,
    category: "Freelance",
    type: "income",
    description: "App UI project",
  },
  {
    id: "25",
    date: "2025-03-14",
    amount: 2200,
    category: "Transport",
    type: "expense",
    description: "Fuel & maintenance",
  },
  {
    id: "26",
    date: "2025-03-16",
    amount: 4500,
    category: "Shopping",
    type: "expense",
    description: "Home decor",
  },
  {
    id: "27",
    date: "2025-03-19",
    amount: 1300,
    category: "Utilities",
    type: "expense",
    description: "Internet & bills",
  },
  {
    id: "28",
    date: "2025-03-21",
    amount: 1800,
    category: "Health",
    type: "expense",
    description: "Medical checkup",
  },
  {
    id: "29",
    date: "2025-03-24",
    amount: 700,
    category: "Entertainment",
    type: "expense",
    description: "Movies & games",
  },
  {
    id: "30",
    date: "2025-03-28",
    amount: 2500,
    category: "Investment",
    type: "income",
    description: "Crypto profit",
  },

  // April
  {
    id: "31",
    date: "2025-04-05",
    amount: 90000,
    category: "Salary",
    type: "income",
    description: "Monthly salary (raise)",
  },
  {
    id: "32",
    date: "2025-04-08",
    amount: 3900,
    category: "Food & Dining",
    type: "expense",
    description: "Groceries & eating out",
  },
  {
    id: "33",
    date: "2025-04-10",
    amount: 12000,
    category: "Housing",
    type: "expense",
    description: "Monthly rent",
  },
  {
    id: "34",
    date: "2025-04-12",
    amount: 1900,
    category: "Transport",
    type: "expense",
    description: "Uber & fuel",
  },
  {
    id: "35",
    date: "2025-04-15",
    amount: 6000,
    category: "Freelance",
    type: "income",
    description: "Dashboard project",
  },
  {
    id: "36",
    date: "2025-04-17",
    amount: 3300,
    category: "Shopping",
    type: "expense",
    description: "Clothes & bags",
  },
  {
    id: "37",
    date: "2025-04-20",
    amount: 1100,
    category: "Utilities",
    type: "expense",
    description: "Monthly bills",
  },
  {
    id: "38",
    date: "2025-04-22",
    amount: 900,
    category: "Entertainment",
    type: "expense",
    description: "OTT subscriptions",
  },
  {
    id: "39",
    date: "2025-04-25",
    amount: 600,
    category: "Health",
    type: "expense",
    description: "Vitamins & pharmacy",
  },
  {
    id: "40",
    date: "2025-04-29",
    amount: 4000,
    category: "Investment",
    type: "income",
    description: "Mutual fund returns",
  },

  // May
  {
    id: "41",
    date: "2025-05-05",
    amount: 90000,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
  },
  {
    id: "42",
    date: "2025-05-07",
    amount: 5200,
    category: "Food & Dining",
    type: "expense",
    description: "Eid shopping & food",
  },
  {
    id: "43",
    date: "2025-05-10",
    amount: 12000,
    category: "Housing",
    type: "expense",
    description: "Monthly rent",
  },
  {
    id: "44",
    date: "2025-05-13",
    amount: 7800,
    category: "Shopping",
    type: "expense",
    description: "Eid clothes & gifts",
  },
  {
    id: "45",
    date: "2025-05-15",
    amount: 2500,
    category: "Transport",
    type: "expense",
    description: "Travel for Eid",
  },
  {
    id: "46",
    date: "2025-05-18",
    amount: 4500,
    category: "Freelance",
    type: "income",
    description: "Mobile app design",
  },
  {
    id: "47",
    date: "2025-05-20",
    amount: 1400,
    category: "Utilities",
    type: "expense",
    description: "Electric & water",
  },
  {
    id: "48",
    date: "2025-05-23",
    amount: 1200,
    category: "Entertainment",
    type: "expense",
    description: "Travel & leisure",
  },
  {
    id: "49",
    date: "2025-05-26",
    amount: 2200,
    category: "Health",
    type: "expense",
    description: "Dental visit",
  },
  {
    id: "50",
    date: "2025-05-29",
    amount: 3500,
    category: "Investment",
    type: "income",
    description: "Bond returns",
  },

  // June
  {
    id: "51",
    date: "2025-06-05",
    amount: 90000,
    category: "Salary",
    type: "income",
    description: "Monthly salary",
  },
  {
    id: "52",
    date: "2025-06-08",
    amount: 4200,
    category: "Food & Dining",
    type: "expense",
    description: "Groceries",
  },
  {
    id: "53",
    date: "2025-06-10",
    amount: 12000,
    category: "Housing",
    type: "expense",
    description: "Monthly rent",
  },
  {
    id: "54",
    date: "2025-06-12",
    amount: 10000,
    category: "Freelance",
    type: "income",
    description: "E-commerce UI project",
  },
  {
    id: "55",
    date: "2025-06-15",
    amount: 2100,
    category: "Transport",
    type: "expense",
    description: "Fuel & ride share",
  },
  {
    id: "56",
    date: "2025-06-18",
    amount: 3800,
    category: "Shopping",
    type: "expense",
    description: "Household items",
  },
  {
    id: "57",
    date: "2025-06-20",
    amount: 1300,
    category: "Utilities",
    type: "expense",
    description: "Electricity bill",
  },
  {
    id: "58",
    date: "2025-06-22",
    amount: 800,
    category: "Entertainment",
    type: "expense",
    description: "Games & streaming",
  },
  {
    id: "59",
    date: "2025-06-25",
    amount: 1500,
    category: "Health",
    type: "expense",
    description: "Health checkup",
  },
  {
    id: "60",
    date: "2025-06-28",
    amount: 5000,
    category: "Investment",
    type: "income",
    description: "Stock market gain",
  },
];
